/**
 * Aeon — The Living Symphony of Earth
 * Pure Frequency Presets & Sound Healing Matrix
 *
 * Provides dedicated acoustic frequency calibrations for meditation,
 * somatic resonance, cellular rejuvenation, and brainwave entrainment.
 */

import { FrequencyPreset, BrainwaveMode } from '../types';

export interface FrequencyPresetInfo {
  hz: number;
  label: string;
  name: string;
  category: 'earth' | 'solfeggio' | 'brainwave' | 'sacred';
  chakra?: string;
  color: string;
  cymaticsGeometry: string;
  description: string;
  benefits: string[];
}

export const FREQUENCY_PRESETS: Record<FrequencyPreset, FrequencyPresetInfo> = {
  hz_7_83: {
    hz: 7.83,
    label: "7.83 Hz",
    name: "Schumann Resonance",
    category: "earth",
    color: "#3ADBC4",
    cymaticsGeometry: "Expanding Planetary Concentric Rings",
    description: "Earth's fundamental electromagnetic pulse resonating between crust and ionosphere.",
    benefits: ["Circadian sync", "Deep Earth grounding", "Biological homeostasis"],
  },
  hz_40: {
    hz: 40,
    label: "40 Hz",
    name: "Gamma Peak Insight",
    category: "brainwave",
    color: "#F6C954",
    cymaticsGeometry: "High-Frequency Crystalline Lattice",
    description: "Cognitive binding frequency associated with intense focus, memory synthesis, and flow.",
    benefits: ["Mental focus", "Memory consolidation", "Heightened awareness"],
  },
  hz_64: {
    hz: 64,
    label: "64 Hz",
    name: "Sub-Bass Earth Anchor",
    category: "earth",
    chakra: "Sub-Physical / Bone",
    color: "#795548",
    cymaticsGeometry: "Hexagonal Sub-Harmonic Pillar",
    description: "Octave harmonic of the 8 Hz Earth pulse. Penetrates skeletal structure and settles chaotic nervous systems.",
    benefits: ["Somatic anchoring", "Bone vibration", "Deep parasympathetic reset"],
  },
  hz_108: {
    hz: 108,
    label: "108 Hz",
    name: "Gongzilla Sacred Symphonic Gong",
    category: "sacred",
    chakra: "Sacred Heart / Universal OM",
    color: "#D4AF37",
    cymaticsGeometry: "108-Rayed Symphonic Solar Mandala",
    description: "The revered Vedic & Tantric Gongzilla master frequency. Rich with crashing metallic brass overtones and ocean swells.",
    benefits: ["Subconscious trauma wash", "Aura sonic cleanse", "Ecstatic gong trance"],
  },
  hz_111: {
    hz: 111,
    label: "111 Hz",
    name: "Cellular Rejuvenation",
    category: "sacred",
    chakra: "Cellular Field",
    color: "#E28743",
    cymaticsGeometry: "Harmonic Trinity Star",
    description: "Known from ancient resonant stone chambers; triggers endorphin release and right-brain hemispheric coherence.",
    benefits: ["Endorphin release", "Deep restorative calm", "Hemispheric balance"],
  },
  hz_128: {
    hz: 128,
    label: "128 Hz",
    name: "Otto Tuner (Nitric Oxide)",
    category: "sacred",
    chakra: "Joints & Spine",
    color: "#009688",
    cymaticsGeometry: "Concentric Acoustic Wavefront",
    description: "Classic osteophonic medical frequency. Stimulates cellular nitric oxide release for vasodilation and muscle release.",
    benefits: ["Nitric oxide release", "Spinal decompression", "Nerve calming"],
  },
  hz_136_1: {
    hz: 136.1,
    label: "136.1 Hz",
    name: "Cosmic OM (Earth Year)",
    category: "earth",
    chakra: "Heart / Soul",
    color: "#4EAA90",
    cymaticsGeometry: "Golden Spiral Torus",
    description: "The 32nd octave of the Earth's orbit around the Sun. Traditional Indian sitar and Tibetan OM root pitch.",
    benefits: ["Profound centering", "Emotional release", "Cosmic alignment"],
  },
  hz_174: {
    hz: 174,
    label: "174 Hz",
    name: "Foundation & Pain Relief",
    category: "solfeggio",
    chakra: "Sub-Root",
    color: "#8B4513",
    cymaticsGeometry: "Stable Cubic Nodal Matrix",
    description: "Natural acoustic anesthetic. Provides physical organs with a deep sense of security, stability, and physical ease.",
    benefits: ["Tension easing", "Physical comfort", "Grounding stability"],
  },
  hz_194_18: {
    hz: 194.18,
    label: "194.18 Hz",
    name: "Synodic Earth Day",
    category: "earth",
    chakra: "Muladhara Base",
    color: "#C0392B",
    cymaticsGeometry: "24-Hour Circadian Helix",
    description: "Calculated by Hans Cousto from the 24-hour planetary rotation. Dynamic, wakeful, energizing biological rhythm.",
    benefits: ["Awakening energy", "Circadian resetting", "Physical stamina"],
  },
  hz_210_42: {
    hz: 210.42,
    label: "210.42 Hz",
    name: "Synodic Moon Resonance",
    category: "earth",
    chakra: "Sacral / Fluid Body",
    color: "#9C27B0",
    cymaticsGeometry: "Crescent Lunar Tides",
    description: "The planetary frequency of the 29.5-day synodic lunar cycle. Modulates bodily fluids, emotional tenderness, and dreams.",
    benefits: ["Emotional release", "Fluid harmony", "Glandular balance"],
  },
  hz_256: {
    hz: 256,
    label: "256 Hz",
    name: "Pythagorean Scientific C",
    category: "sacred",
    chakra: "Harmonic Spine",
    color: "#3F51B5",
    cymaticsGeometry: "Pure Octave Binary Grid",
    description: "Power-of-two (2^8) acoustic standard championed by Verdi and Kepler. Integrates physics with tonal sacred harmony.",
    benefits: ["Mental clarity", "Geometric symmetry", "Auditory purity"],
  },
  hz_285: {
    hz: 285,
    label: "285 Hz",
    name: "Quantum Cellular Renewal",
    category: "solfeggio",
    chakra: "Etheric Body",
    color: "#C25975",
    cymaticsGeometry: "Hexagonal Bio-Grid",
    description: "Restores the energetic blueprint in stressed tissue and sends vibrational instructions for cellular rejuvenation.",
    benefits: ["Cellular rejuvenation", "Vitality boost", "Field regeneration"],
  },
  hz_320: {
    hz: 320,
    label: "320 Hz",
    name: "Solar Plexus Empowerment",
    category: "sacred",
    chakra: "Manipura (Solar Plexus)",
    color: "#FF9800",
    cymaticsGeometry: "Radiant Sunburst Star",
    description: "Golden mean overtone of the 40 Hz gamma rhythm. Awakens personal resolve, digestion, and core vitality.",
    benefits: ["Willpower ignition", "Digestive fire", "Self-confidence"],
  },
  hz_396: {
    hz: 396,
    label: "396 Hz",
    name: "Liberation from Fear & Guilt",
    category: "solfeggio",
    chakra: "Muladhara (Root)",
    color: "#E74C3C",
    cymaticsGeometry: "4-Petaled Earth Mandala",
    description: "Cleanses subconscious guilt, dissolves defensive psychological barriers, and transmutes grief into confidence.",
    benefits: ["Releases guilt & fear", "Root stability", "Empowered security"],
  },
  hz_417: {
    hz: 417,
    label: "417 Hz",
    name: "Facilitating Change & Transmutation",
    category: "solfeggio",
    chakra: "Svadhisthana (Sacral)",
    color: "#E67E22",
    cymaticsGeometry: "6-Petaled Water Crest",
    description: "Wipes out traumatic life events and crystallized emotional blocks, enabling positive flowing transformation.",
    benefits: ["Clears negative blocks", "Creative flow", "Embracing change"],
  },
  hz_432: {
    hz: 432,
    label: "432 Hz",
    name: "Verdi Sacred Nature Harmony",
    category: "sacred",
    chakra: "All Chakras / Golden Mean",
    color: "#F39C12",
    cymaticsGeometry: "12-Petaled Flower of Life",
    description: "Mathematically coherent with Fibonacci ratios, water crystallization, and the golden proportion of biological life.",
    benefits: ["Cardiac coherence", "Natural deep calm", "Fibonacci water resonance"],
  },
  hz_440: {
    hz: 440,
    label: "440 Hz",
    name: "Concert A Reference Pitch",
    category: "sacred",
    chakra: "Auditory Center",
    color: "#607D8B",
    cymaticsGeometry: "Standard Orthogonal Nodal Grid",
    description: "The modern international standard acoustic pitch (ISO 16). Clear, bright, and universally recognized.",
    benefits: ["Acoustic calibration", "Pitch recognition", "Modern concert reference"],
  },
  hz_528: {
    hz: 528,
    label: "528 Hz",
    name: "The Miracle Tone (DNA Transformation)",
    category: "solfeggio",
    chakra: "Anahata (Heart)",
    color: "#2ECC71",
    cymaticsGeometry: "Hexagonal Golden Rose",
    description: "The celebrated love frequency. Widely used in biochemical resonance research to promote cellular vitality and harmony.",
    benefits: ["Heart opening", "Inner peace", "DNA vitality & cellular repair"],
  },
  hz_639: {
    hz: 639,
    label: "639 Hz",
    name: "Harmonious Relationships & Empathy",
    category: "solfeggio",
    chakra: "Vishuddha / Heart Bridge",
    color: "#1ABC9C",
    cymaticsGeometry: "Dual Interlocking Triangles",
    description: "Enables harmonious interpersonal bonds, dissolves emotional estrangement, and deepens heartfelt listening.",
    benefits: ["Compassion & empathy", "Heals relational friction", "Unconditional connection"],
  },
  hz_741: {
    hz: 741,
    label: "741 Hz",
    name: "Awakening Intuition & Detox",
    category: "solfeggio",
    chakra: "Vishuddha (Throat)",
    color: "#3498DB",
    cymaticsGeometry: "16-Spoke Acoustic Crystal",
    description: "Acts as a vibrational shield against electromagnetic clutter, cleanses toxins, and unlocks authentic voice.",
    benefits: ["Throat expression", "Cellular detox", "Intuitive clarity"],
  },
  hz_852: {
    hz: 852,
    label: "852 Hz",
    name: "Spiritual Order & Inner Vision",
    category: "solfeggio",
    chakra: "Ajna (Third Eye)",
    color: "#9B59B6",
    cymaticsGeometry: "Nested Eye of Providence",
    description: "Dissolves mental illusions, re-establishes spiritual clarity, and awakens deep third-eye sight.",
    benefits: ["Third-eye awakening", "Mental stillness", "Spiritual discernment"],
  },
  hz_963: {
    hz: 963,
    label: "963 Hz",
    name: "Pure Cosmic Transcendence",
    category: "solfeggio",
    chakra: "Sahasrara (Crown)",
    color: "#E056FD",
    cymaticsGeometry: "1000-Petaled Radiance",
    description: "Connects individual consciousness with the unified field of light. Awakening of unconditional unity and bliss.",
    benefits: ["Crown activation", "Unity consciousness", "Transcendent stillness"],
  },
  hz_1074: {
    hz: 1074,
    label: "1074 Hz",
    name: "Transpersonal Light Field",
    category: "sacred",
    chakra: "Soul Star Chakra",
    color: "#FF4081",
    cymaticsGeometry: "Hyper-Dimensional MerKaBa",
    description: "High ethereal overtone resonating above the physical crown. Awakens transpersonal clarity and multidimensional perception.",
    benefits: ["Ethereal lightness", "Soul star activation", "Expanded awareness"],
  },
  custom: {
    hz: 528,
    label: "Custom",
    name: "Dialed Frequency Wand",
    category: "sacred",
    color: "#3ADBC4",
    cymaticsGeometry: "Dynamic Wave Interference Pattern",
    description: "Freely sculpted continuous oscillator tuned to your exact chosen acoustic frequency in Hertz.",
    benefits: ["Custom therapeutic work", "Fine micro-tuning", "Exploratory resonance"],
  },
  none: {
    hz: 0,
    label: "Off",
    name: "Natural Earth Symphony Only",
    category: "earth",
    color: "#64748B",
    cymaticsGeometry: "Harmonic Wave Field",
    description: "Pure generative planetary soundscape driven strictly by live global conditions.",
    benefits: ["Natural acoustic immersion", "World telemetry resonance"],
  },
};

export interface BrainwavePresetInfo {
  mode: BrainwaveMode;
  name: string;
  range: string;
  beatHz: number;
  description: string;
  state: string;
}

export const BRAINWAVE_PRESETS: BrainwavePresetInfo[] = [
  {
    mode: 'delta',
    name: 'Delta Waves',
    range: '0.5 – 4.0 Hz',
    beatHz: 2.5,
    description: 'Deep restorative dreamless sleep, pain attenuation, immune recovery.',
    state: 'Deep Sleep & Somatic Healing',
  },
  {
    mode: 'theta',
    name: 'Theta Waves',
    range: '4.0 – 8.0 Hz',
    beatHz: 5.5,
    description: 'Deep meditation, REM hypnagogic imagery, creative breakthroughs, reduced cortisol.',
    state: 'Deep Trance & Intuition',
  },
  {
    mode: 'schumann',
    name: 'Schumann Resonance',
    range: '7.83 Hz exact',
    beatHz: 7.83,
    description: "Earth's ionospheric pulse. Synchronizes biological rhythms with the planet.",
    state: 'Earth Pulse Entrainment',
  },
  {
    mode: 'alpha',
    name: 'Alpha Waves',
    range: '8.0 – 13.0 Hz',
    beatHz: 10.0,
    description: 'Calm alertness, flow state, effortless concentration, reduced anxiety.',
    state: 'Relaxed Focus & Flow State',
  },
  {
    mode: 'beta',
    name: 'Beta Waves',
    range: '14.0 – 30.0 Hz',
    beatHz: 18.0,
    description: 'Active analytical cognitive processing, problem solving, decision making.',
    state: 'Active Cognitive Clarity',
  },
  {
    mode: 'gamma',
    name: 'Gamma Waves',
    range: '30.0 – 50.0 Hz',
    beatHz: 40.0,
    description: 'Peak information processing, high-level cognition, unified sensory perception.',
    state: 'Peak Transcendence & Insight',
  },
];

